package com.arindom.stategenie.processors

import com.squareup.kotlinpoet.ClassName

internal data class ProgaurdConfig(
    private val targetClass: ClassName,
    private val extensiveName: String,
    private val extensiveConstructorParam: List<String>
) {
    internal val outputFile =
        "META-INF/proguard/geniestate-${targetClass.canonicalName}-$extensiveName.pro"

    internal fun writeTo(out: Appendable): Unit =
        out.run {
            appendLine(
                "# This file was generated by geneistate (https://github.com/ArindomGhosh/StateGenie). \n" +
                        "# Do not modify this file."
            )
            //
            // -if class {the target class}
            // -keepnames class {the target class}
            // -if class {the target class}
            // -keep class {the generated sealed extensive class} {
            //    <init>(...);
            // }
            //

            val targetName = targetClass.reflectionName()
            val sealedExtensiveCanonicalName =
                ClassName(targetClass.packageName, extensiveName).canonicalName
            // Keep the class or interface name for SealedX's reflective lookup based on it
            appendLine("-if interface $targetName")
            appendLine("-keepnames interface $targetName")

            appendLine("-if interface $targetName")
            appendLine("-keep interface $sealedExtensiveCanonicalName {")
            // Keep the constructor for SealedX's reflective lookup
            val constructorArgs = extensiveConstructorParam.joinToString(",")
            appendLine("    public <init>($constructorArgs);")
            appendLine("}")
        }
}